# Generated by Django 6.0.1 on 2026-02-12 06:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, help_text='Plain-text list of deliverables / tasks')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Capstone Project',
                'verbose_name_plural': 'Capstone Projects',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('learning_objectives', models.JSONField(default=list)),
                ('theoretical_content', models.TextField()),
                ('practical_exercises', models.JSONField(default=list)),
                ('resources', models.JSONField(default=list)),
                ('estimated_time', models.CharField(max_length=50)),
                ('prerequisites', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Module',
                'verbose_name_plural': 'Course Modules',
                'ordering': ['module_number'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('course_title', models.CharField(max_length=200)),
                ('course_description', models.TextField(blank=True)),
                ('estimated_duration', models.CharField(blank=True, max_length=50)),
                ('skills_covered', models.JSONField(default=list)),
                ('total_modules', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generated Course',
                'verbose_name_plural': 'Generated Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('theory_read', models.BooleanField(default=False)),
                ('exercises_completed', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Module Progress',
                'verbose_name_plural': 'Module Progress Records',
                'ordering': ['module__module_number'],
            },
        ),
        migrations.CreateModel(
            name='ModuleQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('questions', models.JSONField(default=list, help_text='Questions with options and answers')),
                ('passing_score', models.IntegerField(default=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Module Quiz',
                'verbose_name_plural': 'Module Quizzes',
            },
        ),
        migrations.CreateModel(
            name='PsychologyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('trait', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Psychology Question',
                'verbose_name_plural': 'Psychology Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('score', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_traits', models.JSONField(blank=True, null=True)),
                ('personality_summary', models.TextField(blank=True, null=True)),
                ('recommended_careers', models.JSONField(blank=True, null=True)),
                ('selected_career', models.CharField(blank=True, max_length=100, null=True)),
                ('career_level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50, null=True)),
                ('last_assessment_date', models.DateTimeField(blank=True, null=True)),
                ('profile_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_module', models.IntegerField(default=0)),
                ('completed_modules', models.JSONField(default=list)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Progress (Deprecated)',
                'verbose_name_plural': 'User Progress Records (Deprecated)',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(help_text='Numeric score (e.g. 1–5)')),
                ('answer_text', models.TextField(blank=True, help_text='Text answer for conversational questions', null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Response',
                'verbose_name_plural': 'User Responses',
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_summary', models.JSONField()),
                ('recommended_careers', models.JSONField()),
                ('strengths', models.JSONField(blank=True, null=True)),
                ('areas_for_development', models.JSONField(blank=True, null=True)),
                ('ai_insights', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Result',
                'verbose_name_plural': 'User Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('current_question_index', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Test Session',
                'verbose_name_plural': 'Test Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CapstoneSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True)),
                ('project_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Needs Revision')], default='submitted', max_length=20)),
                ('feedback', models.TextField(blank=True, help_text='Reviewer feedback')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('capstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ai_engine.capstoneproject')),
            ],
            options={
                'verbose_name': 'Capstone Submission',
                'verbose_name_plural': 'Capstone Submissions',
            },
        ),
    ]
